#!/bin/sh
### BEGIN INIT INFO
# Provides:          nexus
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start nexus daemon at boot time
# Description:       Enable nexus as a system service provided by daemon.
### END INIT INFO

NEXUS_HOME="/home/pi/nexus/nexus-3.0.0-SNAPSHOT"
NEXUS_USER="pi"

exec sudo -u "$NEXUS_USER" -- "$NEXUS_HOME/bin/nexus" "$@"
