name: 'Link Check'

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  schedule:
    - cron: '34 12 * * *'

jobs:
  link-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Verify muffet filter wrapper is found
        run: |
          WRAPPER_FILENAME="mfw"
          WRAPPER="./.muffet-filter/$WRAPPER_FILENAME"  
          if test -f "$WRAPPER"; then
            echo "using wrapper $WRAPPER"
          else
            PROJECT_URL="https://github.com/bhamail/muffet-filter"
            echo "Missing muffet-filter wrapper file $WRAPPER. Download here: $PROJECT_URL" && exit 1
          fi
      - name: Run muffet filter wrapper
        #see ./.muffet-filter/ignores.json for the list of ignored links
        run: ./.muffet-filter/mfw --ignore-empty-err-url https://bhamail.github.io/pinexus/
